networks:
  app-network:
    driver: bridge
    name: app-network

services:

  # Application services
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4242:80" # http
      #- "4243:443"  https
    volumes:
      - ./srcs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build: ./srcs/backend
    container_name: backend
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - ./srcs/backend:/app


  frontend:
    build: ./srcs/frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./srcs/frontend:/app






