networks:
  
  app-network:
    driver: bridge
    name: app-network
  
  #monitoring-network:
  #  driver: bridge
  #  name: monitoring-network


volumes:
  grafana-storage:


services:

  # Application services
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4242:80" # http
      #- "4243:443"  https
    volumes:
      - ./srcs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
      - monitoring-network

  backend:
    build: ./srcs/backend
    container_name: backend
    expose:
      - "8000"
    networks:
      - app-network
    volumes:
      - ./srcs/backend/app:/app


  frontend:
    build: ./srcs/frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - app-network
    volumes:
      - ./srcs/frontend/app:/app




  # Monitoring services
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./srcs/server-tools/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
      - GF_UPDATE_CHECK=false
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    networks:
      - app-network





