
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Scrape Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape backend
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  # Scrape frontend
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  # Scrape Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
